### ISSUE TITLE
Backend settings

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-welcomebot#5] opened 2019-01-28 09:47 UTC
Any ETA for bot config in MM console?

**Comment by hanzei** [comment] 2019-01-28 09:50
Hey @uhlhosting,

Are you referring to bot accounts for Mattermost?

**Comment by uhlhosting** [comment] 2019-01-28 10:47
For the welcome bot settings need to be done via config.json and thats quite not so at hand always. Best would be to manage settings in Console backend.

**Comment by hanzei** [comment] 2019-01-28 11:09
This needs changes on the Mattermost server. See https://mattermost.atlassian.net/browse/MM-11828 for more context.

**Comment by franckadil** [comment] 2020-03-19 20:09
@hanzei Hi guys, I tried to add the sample message but Mattermost keeps failing. I tried to put the script in settings as explained but it seems that I am just doing it wrong. 

Can any of please share their confi.json with me or a full screenshot please ?

Thank you in advance for your help!

Cheers,

**Comment by hanzei** [comment] 2020-03-20 09:51
Hey @franckadil,

Did you modify your `config.json` according to https://github.com/mattermost/mattermost-plugin-welcomebot#usage? If not, would you mind opening a new issue, given that your questions is more like a new  support request?

**Comment by franckadil** [comment] 2020-03-20 12:57
Hi @hanzei thank you for your prompt reply. I have reached  out yesterday to the community channel in Mattermost, and it appears that the example on the documentation had some errors in it. I implemented the corrections and now it perfectly works! I've seen also that a commit have been done on the Readme.md so that's good  now.

**Comment by hanzei** [comment] 2021-06-30 13:22
Duplicates  https://github.com/mattermost/mattermost-plugin-welcomebot/issues/42

**Comment by hanzei** [comment] 2021-06-30 13:23
Duplicate of #42

**Closed** 2021-06-30 13:23 UTC
Labels: Needs Mattermost Changes, Type/Enhancement
